# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lat_long.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elat_long.proto\x12\x0clat_long_api\"\x1d\n\nLatLon_req\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"1\n\nLatLon_res\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x32T\n\x0eLatLongService\x12\x42\n\nGetLatLong\x12\x18.lat_long_api.LatLon_req\x1a\x18.lat_long_api.LatLon_res\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lat_long_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LATLON_REQ']._serialized_start=32
  _globals['_LATLON_REQ']._serialized_end=61
  _globals['_LATLON_RES']._serialized_start=63
  _globals['_LATLON_RES']._serialized_end=112
  _globals['_LATLONGSERVICE']._serialized_start=114
  _globals['_LATLONGSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
