# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lat_long_pb2 as lat__long__pb2


class LatLongServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatLong = channel.unary_unary(
                '/lat_long_api.LatLongService/GetLatLong',
                request_serializer=lat__long__pb2.LatLon_req.SerializeToString,
                response_deserializer=lat__long__pb2.LatLon_res.FromString,
                )


class LatLongServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LatLongServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatLong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatLong,
                    request_deserializer=lat__long__pb2.LatLon_req.FromString,
                    response_serializer=lat__long__pb2.LatLon_res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lat_long_api.LatLongService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LatLongService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lat_long_api.LatLongService/GetLatLong',
            lat__long__pb2.LatLon_req.SerializeToString,
            lat__long__pb2.LatLon_res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
