# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/users.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/users.proto\x12\x05users\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x87\x01\n\x17RestaurantSearchRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x13\n\x0b\x63\x61tegorySet\x18\x03 \x01(\x05\x12\x0c\n\x04view\x18\x04 \x01(\t\x12\x13\n\x0brelatedPois\x18\x05 \x01(\t\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\r\n\x05limit\x18\x07 \x01(\x05\",\n\x18RestaurantSearchResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xb4\x03\n\x05Users\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x00\x12U\n\x10RestaurantSearch\x12\x1e.users.RestaurantSearchRequest\x1a\x1f.users.RestaurantSearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=29
  _globals['_USER']._serialized_end=94
  _globals['_GETUSERSREQUEST']._serialized_start=96
  _globals['_GETUSERSREQUEST']._serialized_end=113
  _globals['_GETUSERSRESPONSE']._serialized_start=115
  _globals['_GETUSERSRESPONSE']._serialized_end=161
  _globals['_GETUSERBYIDREQUEST']._serialized_start=163
  _globals['_GETUSERBYIDREQUEST']._serialized_end=195
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=197
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=245
  _globals['_CREATEUSERREQUEST']._serialized_start=247
  _globals['_CREATEUSERREQUEST']._serialized_end=293
  _globals['_CREATEUSERRESPONSE']._serialized_start=295
  _globals['_CREATEUSERRESPONSE']._serialized_end=342
  _globals['_UPDATEUSERREQUEST']._serialized_start=344
  _globals['_UPDATEUSERREQUEST']._serialized_end=390
  _globals['_UPDATEUSERRESPONSE']._serialized_start=392
  _globals['_UPDATEUSERRESPONSE']._serialized_end=439
  _globals['_DELETEUSERREQUEST']._serialized_start=441
  _globals['_DELETEUSERREQUEST']._serialized_end=472
  _globals['_DELETEUSERRESPONSE']._serialized_start=474
  _globals['_DELETEUSERRESPONSE']._serialized_end=521
  _globals['_RESTAURANTSEARCHREQUEST']._serialized_start=524
  _globals['_RESTAURANTSEARCHREQUEST']._serialized_end=659
  _globals['_RESTAURANTSEARCHRESPONSE']._serialized_start=661
  _globals['_RESTAURANTSEARCHRESPONSE']._serialized_end=705
  _globals['_USERS']._serialized_start=708
  _globals['_USERS']._serialized_end=1144
# @@protoc_insertion_point(module_scope)
